name: RunForMoney
version: 1.0.1
main: runner.RunForMoney

commands:
   rfm:
      description: Administration command of Run For Money
      usage: /<command> addhunter, addrunner,  status, start, stop, reset
      permission: runformoney.admin
      permission-message: You don't have <permission>