name: RunForMoney
version: 1.0.3
main: runner.RunForMoney

commands:
   rfm:
      description: Administration command of Run For Money
      usage: type "/<command> help" to see more 
      permission: runformoney.admin
      permission-message: You don't have <permission>
   join:
      description: Join command of Run For Money
      usage: /<command>
      permission:
      permission-message: You don't have <permission>
